### ISSUE TITLE
In C 4.3.9 Modul Sitemap fehlerhafte Darstellung

### ISSUE THREAD

**Issue by green-pixelbox** [contao/managed-edition#10]
In dem Modul Sitemap werden Seiten dargestellt, die als "In der Sitemap zeigen" -> "Nie anzeigen" deklariert sind. Angewählt bei der Seiteneinstellung ist auch "Menü verstecken" und "Seite veröffentlichen".

**Comment by leofeyer** [comment]
Siehe contao/core-bundle#818.
