### ISSUE TITLE
files-Symlink wird nicht erstellt

### ISSUE THREAD

**Issue by Xendiadyon** [contao/managed-edition#11]
Ich habe heute mal die contao managed-edition installiert. Frische Installation.

Hat es einen Sinn, dass der symlink von managed-edition/web/files auf managed-edition/files fehlt?
Ich versuche die ganze Zeit, den files-Ordner per web aufzurufen...

![image](https://cloud.githubusercontent.com/assets/2657385/26158464/3f66d666-3b1c-11e7-90f0-62cf7fc18c23.png)

**Comment by leofeyer** [comment]
Hast Du denn irgendwelche öffentlichen Ordner angelegt?

**Comment by Xendiadyon** [comment]
Danke, das war's. Es wird nicht mehr files direkt versymlinkt, sondern die Unterordner, bei denen man in der Contao-Backend-Dateiverwaltung ausgewählt hat, dass sie über http erreichbar sein sollen.

Wieder was gelernt :)

![image](https://cloud.githubusercontent.com/assets/2657385/26200127/1da98828-3bcd-11e7-82ad-fad1386ab433.png)
