### ISSUE TITLE
Fehlermeldung nach Absenden eines Formulares

### ISSUE THREAD

**Issue by ngdot** [contao/managed-edition#12]
Hi,

habe ein einfaches Formular erstellt welches per E-Mail versendet werden soll, sobald ich es abschicke bekomme ich im Frontend die Fehlerseite und im Log steht folgendes:

app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"newInstance\" of class \"Swift_Message\". at /var/www/html/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Email.php:125)"} []

**Comment by aschempp** [comment]
see https://github.com/contao/core-bundle/issues/843
