### ISSUE TITLE
prepend_locale

### ISSUE THREAD

**Issue by daniel-nemeth** [contao/managed-edition#13]
Hi,
how is it possible to avoid the locale to be added automatically?
Since this option is set to true by default I have some issues adding JS files from "files" folder.

I tried to add "prepend_locale: false" to config and then clear the cache via the Maintenance but it doesn't worked for me.

Thanks

**Comment by xchs** [comment]
Did you add `prepend_locale: false` to the `app/config/parameters.yml` configuration file?

**Comment by daniel-nemeth** [comment]
I got the problem. I had to clear the cache via vendor/bin/contao-console cache:clear -e=prod, not only via the maintenance module in backend. Then its important to clear the browser cache too. After this all works fine.

Sorry for being to lazy to clear the cache via console first.
Thx xchs!

**Comment by fritzmg** [comment]
Just fyi, in Contao 4.4 the default will be false again.

**Comment by daniel-nemeth** [comment]
Ok!
Thx for your great job all!
