### ISSUE TITLE
app/console doctrine:cache:clear contao.cache is not working

### ISSUE THREAD

**Issue by WolfNik** [contao/managed-edition#14]
installed managed edition but app/console doctrine:cache:clear contao.cache is not working, there is no console under app/ while I entered 3 times wrong password on install tool

**Comment by xchs** [comment]
You have to run the scripts via `vendor/bin/*`, e.g.
```
vendor/bin/contao-console cache:clear
```

**Comment by WolfNik** [comment]
that worked as a sudo and afterwards setting the ownership new.

Please change this on the error-message

**Comment by aschempp** [comment]
What error message?

**Comment by WolfNik** [comment]
When install is blocked it says please run: app/console doctrine:cache:clear contao.cache
(just enter 3 time a wrong password at the install screen)

This is not working. 

vendor/bin/contao-console cache:clear was working but had to run as sudo and afterwards do a chown on the contao to the web-user in my case www-data:www-data

**Comment by aschempp** [comment]
What do you mean by "install is blocked"? I have never seen such a message.

**Comment by WolfNik** [comment]
install the managed edition, after installing and login go back to /contao/install. 
Then you are asked for the install password. 
Type 3 times a wrong one.
Then reload /contao/install again.
Now it says: Please run app/console doctrine:cache:clear contao.cache

This was not working for me

**Comment by aschempp** [comment]
You're right, very strange. I have no idea why this command should fix the issue anyway :D

**Comment by WolfNik** [comment]
Best solution would be to put an option to the system settings. But this command was not helpful and you find no advice when you search in google. So as a first step change the message to something working.

**Comment by leofeyer** [comment]
This is actually just another reason why we should have a `bin/console` entry point.

<img width="803" alt="" src="https://cloud.githubusercontent.com/assets/1192057/26573206/23b5f676-451d-11e7-90f6-32b5651bd003.png">

The error message is correct for the SE but not for the ME. @contao/developers /cc

**Comment by leofeyer** [comment]
As discussed in Mumble on July 13th, we should use a simple file locking similar to the Lexik maintenance bundle.

**Comment by srhinow** [comment]
Contao 4.4.7
PHP 7.1

Das funktioniert bei mir für die Standart-Edition genauso wenig. Er rödelt zwar kurz nach dem Befehl aber die Block-Fehlermeldung bleibt die selbe.
Wenn ich den Befehlt mehrmals ausführe kommt auch immer:
`% bin/console doctrine:cache:clear contao.cache
Clearing the cache for the contao.cache provider of type Doctrine\Common\Cache\FilesystemCache
`
Aber die Sperre bleibt bestehen. 

Auch was in der Anleitung (https://docs.contao.org/books/manual/current/de/01-installation/contao-installieren.html#das-contao-installtool) steht funktioniert nicht.

**Comment by fritzmg** [comment]
I can confirm that running
```
bin/console doctrine:cache:clear contao.cache
```
in the Contao Standard Edition does not unlock the Install Tool (once locked).

**Comment by fritzmg** [comment]
@srhinow what the messages does not tell you is that the `bin/console` of Symfony runs in the `dev` environment by default (see [bin/console#L18](https://github.com/symfony/symfony-standard/blob/v3.3.10/bin/console#L18)). Unlike in the Contao Managed Edition, where the `contao-console` runs in the `prod` environment by default. Thus if you want to unlock the Install Tool for the `prod` environment you actually have to run
```
bin/console doctrine:cache:clear contao.cache --env=prod
```
(or `-e=prod`).

If you want the `bin/console` to be run in the `prod` environment by default, then you have to set the `SYMFONY_ENV` environment variable (for the PHP CLI) to `prod`.

See also https://github.com/contao/core-bundle/issues/1088

**Comment by srhinow** [comment]
i think that i have the Standart-edition and i try all of eny comands with --env=prod and without as sudo  and without.
Where is the SYMFONY_ENV -vaiable? Why can i not reset the install-pw in eny environment?
What is the different between standart-edition and the managed-edition. I just did want a current Contao 4 installation anymore.

**Comment by fritzmg** [comment]
> i think that i have the Standart-edition and i try all of eny comands with --env=prod and without as sudo and without.

Are you sure you have used the following command:
```
bin/console doctrine:cache:clear contao.cache --env=prod
```
This works as far as I have tested.

> Where is the SYMFONY_ENV -vaiable?

It is an environment variable set by your operating system.

> What is the different between standart-edition and the managed-edition. I just did want a current Contao 4 installation anymore.

If you just want Contao, you are probably better off with the managed edition. But that depends on your specific requirements.

**Comment by ghost** [comment]
The issue has been moved to contao/installation-bundle#73.
