### ISSUE TITLE
Intergrierter Web-Server funktioniert nicht mehr (vendor/bin/contao-console server:run)

### ISSUE THREAD

**Issue by ghost** [contao/managed-edition#15]
<a href="https://github.com/LinkingYou"><img src="https://avatars2.githubusercontent.com/u/23259908?v=3" align="left" width="42" height="42"></img></a> [Issue](https://github.com/contao/core-bundle/issues/861) by @LinkingYou
June 2nd, 2017, 19:55 GMT

In der aktuellen Version 4.3.11 (Managed-Edition) funktioniert der integrierte Web-Server nicht mehr:

`php vendor/bin/contao-console server:run`

bringt folgenden Fehler:
                                                                  
```
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "server" namespace.   
```

Ist das beabsichtigt?

**Comment by LinkingYou** [comment]
Ist wohl auch wieder eine Inkompatibilität zu Symfony 3.3.

Nachdem ich ein 

```
    "conflict": {
        "symfony/symfony": ">=3.3"
    },
```

in die composer.json eingefügt habe, geht auch der "server" wieder.

**Comment by Toflar** [comment]
In Symfony 3.3 wurde der Server Command in das `WebServerBundle` verschoben. Deswegen gibt es das Command nicht mehr, da dieses Bundle (noch) nicht registriert wird. Ich weiss aber ehrlich gesagt auch gar nicht ob wir das tun sollten.

**Comment by LinkingYou** [comment]
Ich nutze den integrierten Server bei allen meinen Symfony-Projekten in der Entwicklungsumgebung und hatte mich gefreut, das auch bei meinen Contao 4 Projekten nutzen zu dürfen. Wäre echt schade, wenn das rausfallen würde. Es gibt für mich keinen schnelleren Weg, eine Entwicklungsumgebung zu erstellen.

**Comment by Toflar** [comment]
Wir können das Bundle einfach im dev Environment laden, analog dem DebugBundle etc. Das kannst du in der Zwischenzeit für dein Projekt [per globalem Plugin](https://docs.contao.org/books/extending-contao4/managed-edition/#adding-a-manager-plugin) ganz einfach selber nachladen :)

@leofeyer bitte Issue zum manager-bundle verschieben.

**Comment by ghost** [comment]
Das Ticket wurde nach contao/manager-bundle#35 verschoben.
