### ISSUE TITLE
.public files only in dev mode?

### ISSUE THREAD

**Issue by Defcon0** [contao/managed-edition#18]
Currently I write a small module for handling scss and css in Contao 4.3. At the moment, this results in a composed css file. Next to that file I generate a .css.map file containing all the references. Unfortunately this file is currently useless because we don't let scss files go into the web folder (which is a good practice I guess). So the references from the map to the scss files is dead.

To my knowledge the way to go for creating symlinks by the contao console is to add a .public file into the folder that should be symlinked to the web folder.

Are these .public files environment independend (which I fear ;-) ) or is there a chance that we can in Contao 4.4 make some of these only be active in dev mode? Could also be a feature request, I'm not sure.

Thanks in advance.

**Comment by backbone87** [comment]
imho you could write a dev env only route with a custom controller that serves the scss file and rewrite the map references to that controller.

**Comment by leofeyer** [comment]
> Are these .public files environment independend

Yes, they are.

> is there a chance that we can in Contao 4.4 make some of these only be active in dev mode?

I don't think so. At least I don't see a real use case here.

**Comment by leofeyer** [comment]
As discussed in Mumble on July 13th, environment dependent symlinks are technically not possible. You would have to do what @backbone87 suggested (or something similar).
