### ISSUE TITLE
in C 4.4 fehlt "Abstand davor und dahinter"

### ISSUE THREAD

**Issue by green-pixelbox** [contao/managed-edition#19]
in C 4.4 fehlt in den Artikeleinstellungen und Elementeinstellungen unter Experteneinstellungen "Abstand davor und dahinter". Oder ist das absichtlich herausgenommen worden?

**Comment by aschempp** [comment]
Die Felder wurden entfernt, siehe https://github.com/contao/core-bundle/blob/master/UPGRADE.md#space-beforeafter
