### ISSUE TITLE
Formulargenerator Checkbox-Menü

### ISSUE THREAD

**Issue by green-pixelbox** [contao/managed-edition#20]
eine checkbox ist im Formular standardmäßig auf "checked" ... bzw. ist standardmäßig angewählt

**Comment by ausi** [comment]
Das konnte ich nicht reproduzieren. In meinem Test ist eine Checkbox nur dann standardmäßig angewählt wenn die Eigenschaft „Standard“ dafür aktiviert wurde.

**Comment by leofeyer** [comment]
@green-pixelbox Wie genau lässt sich das Problem reproduzieren?

**Comment by green-pixelbox** [comment]
ich hatte leider nicht mehr auf dem Schirm dass die Eigenschaft "Standard" das regelt ob eine Checkbox angewählt sein soll oder nicht. Also alles gut, funktioniert. Danke fürs Nachschauen.
