### ISSUE TITLE
Seitenstruktur "Interne Weiterleitung" keine Seitenauswahl möglich

### ISSUE THREAD

**Issue by green-pixelbox** [contao/managed-edition#21]
In der Seitenstruktur bei "internen Weiterleitungen" kann man unter "Weiterleitung" -> "Weiterleitungsseite" zwar die Ansicht der Seiten ansehen, aber keine Seite auswählen

**Comment by aschempp** [comment]
Duplicate of https://github.com/contao/core-bundle/issues/883
