### ISSUE TITLE
Auswahl "Link-Adresse" oder "Bildllink" bei Benutzer "kein Administrator" fehlerhaft

### ISSUE THREAD

**Issue by green-pixelbox** [contao/managed-edition#22]
Wenn ein Benutzer kein Administrator ist, kann er zB bei dem Element "hyperlink" keine "Link-Adresse" auswählen oder bei einem Bildelement kein "Bildlink". NAch einem Klick auf die "blaue Weltkugel" erscheint dann eine Fehlermeldung (siehe Screenshot bildlink_fehlermeldung) anbei. Leider weiss ich noch nicht, wie man eine "richtige Fehlermeldung" ausgeben kann, sodass ich euch leider nur diesen Hinweis geben kann.

![bildlink01](https://user-images.githubusercontent.com/3920742/27868683-c4b7f078-619d-11e7-9b98-088b5e605d56.JPG)
![bildlink02](https://user-images.githubusercontent.com/3920742/27868686-c79588b4-619d-11e7-984f-538afe8afac4.JPG)
![bildlink_fehlermeldung](https://user-images.githubusercontent.com/3920742/27868688-c9d3850e-619d-11e7-94fe-938ab1be4856.JPG)

**Comment by leofeyer** [comment]
Siehe https://github.com/contao/core-bundle/pull/906, https://github.com/contao/core-bundle/issues/883, https://github.com/contao/core-bundle/issues/904, https://github.com/contao/core-bundle/issues/899, https://github.com/contao/managed-edition/issues/21 und https://github.com/contao/core-bundle/issue/927.

**Comment by green-pixelbox** [comment]
habe das Update auf C 4.4.1 gemacht, jetzt zeigt Contao zwar die Seitenstruktur an, aber eine Auswahl einer Seite ist leider immer noch nicht möglich. Das ist sogar aus so, wenn man Administrator ist.
![c441_bildlink](https://user-images.githubusercontent.com/3920742/28115356-e648d632-6704-11e7-860e-b50e0bc3137c.JPG)

**Comment by leofeyer** [comment]
https://contao.org/de/news/contao_4-4-1.html

**DCA-Picker**

Der in Contao 4.4.0 neu eingeführte DCA-Picker ist in Contao 4.4.1 leider weiterhin nicht für reguläre Backend-Benutzer nutzbar.

Um das Problem zu beheben, müssen wir die Implementierung komplett überarbeiten (siehe contao/core-bundle#950), daher bitten wir alle Entwickler, noch keine Erweiterungen zu veröffentlichen, die den neuen Picker nutzen. Die neue Implementierung kann aus technischen Gründen nicht rückwärtskompatibel sein.
