### ISSUE TITLE
PHP Fehlermeldungen werden auf dem Bildschirm ausgegeben

### ISSUE THREAD

**Issue by Mynyx** [contao/managed-edition#24]
PHP Fehlermeldungen werden stets auf dem Bildschirm ausgegeben, eine Konfigurationsmöglichkeit wie in Contao 3.5 fehlt.

**Comment by aschempp** [comment]
Das sollte eigentlich nicht der Fall sein? Die Ausgabe von Fehlern hängt davon ab welchen Entry Point du benutzt, ob `app.php` oder `app_dev.php`?

**Comment by Mynyx** [comment]
Ich benutze den ``app.php`` Entry Point.

**Comment by ausi** [comment]
Kann ich bestätigen, der *app.php* entry point zeigt fehlermeldungen an:

![contao-error](https://user-images.githubusercontent.com/367169/28337120-d26be23a-6c04-11e7-90cf-f0d691626568.png)

Ist aber vermutlich ein contao/core-bundle issue unabhängig von der managed edition.

**Comment by aschempp** [comment]
Ihr meint die Meldung die im Inhalt steht? Das ist nur im Backend/bei abgemeldetem Benutzer der Fall 😉

**Comment by ausi** [comment]
Stimmt, sorry. Im frontend wird keine Fehlermeldung ausgegeben 👍

**Comment by leofeyer** [comment]
Das ist doch auch keine PHP-Fehlermeldung, sondern unsere Pretty Error Screen.

**Comment by Mynyx** [comment]
Nein, ich meine native PHP Fehlermeldungen.

**Comment by ausi** [comment]
> Das ist doch auch keine PHP-Fehlermeldung, sondern unsere Pretty Error Screen.

Im pretty error screen vom backend wird die message der exception ausgegeben, das betrifft auch PHP-Fehlermeldungen. Allerdings ist das auch in Ordnung so denke ich, da es nur das Backend betrifft.

> Nein, ich meine native PHP Fehlermeldungen.

Kannst du ein Beispiel nennen wie man das reproduzieren kann? Und eventuell einen screenshot zeigen damit wir von der selben Art von Fehlermeldung sprechen?

**Comment by leofeyer** [comment]
Aber der Pretty-Error-Handler ist doch auch im Frontend aktiv, oder?

**Comment by ausi** [comment]
Ja, aber im Frontend wird nicht das Backend-Error-Template geladen ([PrettyErrorScreenListener.php:124](https://github.com/contao/core-bundle/blob/2a85914f4ba858780ffbac38a468acb7028772c7/src/EventListener/PrettyErrorScreenListener.php#L124)) und nur im backend template wird die fehlermeldung ausgegeben...

**Comment by leofeyer** [comment]
Müssen wir also etwas ändern oder kann ich das Ticket schließen?

**Comment by ausi** [comment]
@Mynyx hat nicht mehr geantwortet auf meine Frage.

IMO kann es geschlossen werden.

**Comment by fritzmg** [comment]
Hm, I just had something like this:

![screen shot 2017-09-16 at 15 36 12](https://user-images.githubusercontent.com/4970961/30512687-11df6f9e-9af5-11e7-8447-e02cc49a7860.png)

@Mynyx did you mean that?

**Comment by dmolineus** [comment]
Can confirm it. Also saw some unformatted fatal errors. Maybe the in PHP 7 introduced throwable errors are not handled correctly? It's just a guess, didn't look into the code.

**Comment by leofeyer** [comment]
How do I reproduce this?

**Comment by dmolineus** [comment]
@leofeyer I think you accidently closed this issue.

~~To repoduce it, just add a syntax error to your code which will throw an fatal error.~~

Hm, no. I can't reproduce it anymore.

**Comment by leofeyer** [comment]
> Hm, no. I can't reproduce it anymore.

Me neither, that's why I closed it. Maybe it was an issue with one of the vendor packages.
