### ISSUE TITLE
Pb with http and https

### ISSUE THREAD

**Issue by vmulot** [contao/managed-edition#26]
Hello,
I'm running contao 4.3.11 on a shared hosting (OVH), it used to work pretty well, but now i'm having issues.
first, the website was "http", and then we activated the https.
In my htaccess i added these lines in the mod_rewrite section
`RewriteCond %{HTTPS} off
    RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]`

if i try to go to backoffice with : https://mywebsite.com/contao/ it redirects me to  http://mywebsite.com:443/contao/login (and this page isn't working)

due to deadline, i had also to edit the fe_page (and backoffice main page also) and write the base tag instead of the contao one so i can have https, otherwise resources were'nt loaded.
But in BO, all the "lightbox" pages are broken.

i tried to clear cache (with console), to update Contao, ... but still the same.
any clue on what is happening here ? is it a Contao issue or a Server issue ?

Thanks

**Comment by fritzmg** [comment]
Is your setup using an SSL proxy?

Also may be related to https://github.com/contao/core-bundle/issues/895

**Comment by vmulot** [comment]
Thanks for answering,

How can i check that ?

**Comment by vmulot** [comment]
Ok, new info , if i remove `$kernel = new ContaoCache($kernel);` from web/app.php it works.
so what should i do ? i presume that if i do a composer update, the app.php will be overwritten ?

i tried with contao managed edition 4.4.2, and i still have the same pb, i need to comment  this line in web/app.php

**Comment by leofeyer** [comment]
See contao/core-bundle#895.
