### ISSUE TITLE
standard image sizes / standard pixel density in theme

### ISSUE THREAD

**Issue by michaelgawlik** [contao/managed-edition#28]
standard image sizes / standard pixel density in theme settings hasn't any effect. If you use the input for pixel density and scaling factor in a specific image size - it works as expected.

**Comment by leofeyer** [comment]
How do I reproduce this in the online demo?

**Comment by michaelgawlik** [comment]
Themes > Settings > Tab: Image sizes

then create an image size and leave the input field for Pixel densities/scale factors blank.

**Comment by fritzmg** [comment]
@dillinja you are misunderstanding this setting. This setting will be used whenever you do __not__ use an image size setting for an image. e.g. if you use one of the other modes, like `proportional`, `box`, `center_center` etc.

See https://github.com/contao/core/issues/8171

**Comment by michaelgawlik** [comment]
ah, I got it. Thank you.
