### ISSUE TITLE
Packaged ZIP file contains escaped front slashes in composer.json -> intended behavior?

### ISSUE THREAD

**Issue by Defcon0** [contao/managed-edition#35]
Hello,

The title says it all ;-) Is this intended behavior or an issue since these back slashes escaping the front slashes aren't included in this repo here.

![screen](https://user-images.githubusercontent.com/1485098/37146014-d8dcb854-22c2-11e8-9dc9-1b6668c3f605.png)

**Comment by leofeyer** [comment]
Nope, that's definitely not intended. 😠

**Comment by leofeyer** [comment]
Fixed in contao/release-helper@fb70f50f519af18769c94cc5e6c296a6d1ab857e.
