### ISSUE TITLE
Using config.component-dir has been deprecated

### ISSUE THREAD

**Issue by rabauss** [contao/managed-edition#37]
In contao 4.4 managed edition we get the following warning:
`Using config.component-dir has been deprecated. Please use extra.contao-component-dir instead.`

The composer.json should be updated for all branches 4.4 + 4.5 like 4.6, shouldn't it?

**Comment by fritzmg** [comment]
It's not an error. It's a deprecation warning. The previous definition within "config" still works. Probably until version `2.x` of [contao-components/installer](https://github.com/contao-components/installer) is released (and used).

**Comment by leofeyer** [comment]
Correct.
