### ISSUE TITLE
On Contao 4.7 no sendmail available

### ISSUE THREAD

**Issue by tinitussi** [contao/managed-edition#40]
Hello,

with contao 4.7 there is no sendmail available
If I set in website/app/config/parameters.yml to mailer_transport: sendmail
the sendmail get the data in a wrong format.
In mail.log I get this:

REMOTE="X:X:X::" SCRIPT=/website/web/app.php -- /usr/sbin/sendmail -bs

in Contao log I get this:
Form "Name" could not be sent: Expected response code 220 but got an empty response

**Comment by leofeyer** [comment]
Contao does not provide sendmail; it is a binary that needs to be installed on your server. Please ask your server admin to install sendmail or configure Contao to send mails via SMTP (recommended).
