### ISSUE TITLE
Contao minor versions are missing - Download fails

### ISSUE THREAD

**Issue by chrinorse** [contao/managed-edition#41]
**Affected version(s)**
All
**Description**  
Download of specific contao version not possible. A look at https://github.com/contao/managed-edition/releases shows no minor version. Am I missing something?
**How to reproduce**  
I try to install contao with the composer. I installed the latest composer version with:
curl -sS https://getcomposer.org/installer | php
and then tried to install conato with:
php composer.phar create-project contao/managed-edition /data/contao 4.4.17
And all I get is:
Could not find package contao/managed-edition with version 4.4.17.
I also tried to install the latest version:
php composer.phar create-project contao/managed-edition /data/contao 4.4.41
Could not find package contao/managed-edition with version 4.4.41.

So I tried to download contao as explained in the docs: https://docs.contao.org/books/manual/current/en/01-installation/installing-contao.html
with:
curl -L http://download.contao.org
I get:
Contao 4.7.3 is not available as .zip download. Please use the Contao Manager or Composer to install Contao. See https://contao.org/en/download.html for more information.

curl -L http://download.contao.org/4.4.17
I get:
Not Found

curl -L http://download.contao.org/4.4.41
I get:
Contao 4.4.41 is not available as .zip download. Please use the Contao Manager or Composer to install Contao. See https://contao.org/en/download.html for more information.

**Comment by fritzmg** [comment]
Your post already contains the answser:

> Contao […] is not available as .zip download. Please use the Contao Manager or Composer to install Contao. See https://contao.org/en/download.html for more information.

**Comment by chrinorse** [comment]
Actually it doesn't, but since you pointed it out as answer, I can only assume that the minor versions have been remove and only 4.4 or 4.7 is available. When did you change that, I am pretty sure, a few days ago, I installed contao as mentioned above?

**Comment by leofeyer** [comment]
We have changed this yesterday, because the tags of the managed edition have (purposefully) not been in sync with the Contao core bundle and people tended to be irritated by that. Also, using the `download.contao.org` URL has been deprecated ever since we had the Contao Manager.

There are two ways to install Contao 4.4+:

1. Contao Manager
2. `php composer.phar create-project contao/managed-edition . 4.4`

**Comment by chrinorse** [comment]
Thanks for the clarification
