### ISSUE TITLE
Broken link in README.md chapter Installation

### ISSUE THREAD

**Issue by Mynyx** [contao/managed-edition#50]
The link to the installation chapter of the user manual is broken (https://github.com/contao/managed-edition/blob/master/README.md#installation).

**Comment by fritzmg** [comment]
Why not provide a PR instead of creating an issue for such a small change? ;)

**Comment by xchs** [comment]
See https://github.com/contao/managed-edition/pull/51

**Comment by Mynyx** [comment]
> Why not provide a PR instead of creating an issue for such a small change? ;)

I was not sure about the correct target of the link...
