### ISSUE TITLE
PHP 8 Compatibility

### ISSUE THREAD

**Issue by ausi** [contao/managed-edition#56]
Should we wait until `contao/contao` is compatible with PHP 8 before adding compatibility here?

**Comment by aschempp** [comment]
Imho we should remove it from this. The Contao Manager does not add a PHP dependency either, because the `contao/manager-bundle` should manage every dependency in a managed edition.

**Comment by fritzmg** [comment]
Isn't this root dependency there to optimise dependency resolving?

**Comment by aschempp** [comment]
in a regular PHP project, yes. But the _Managed Edition_ is not a regular project, the `composer.json` should be the bare minimum and the `contao/manager-bundle` configures everything.

**Comment by leofeyer** [comment]
I have removed the PHP version requirement in the 4.9, 4.10 and the master branch.
