### ISSUE TITLE
Dateiverwaltung Ordnernamen mit Leerzeichen

### ISSUE THREAD

**Issue by green-pixelbox** [contao/managed-edition#8]
Hallo. Bei der Dateiverwaltung Ordnernamen mit Leerzeichen produziert einen Fehler. Möchte man einen neuen Ordner erstellen in den Ordner mit Leerzeichen, bekomme ich folgende Fehlermeldung:
File or folder "files/gasthof-zur-post/test%20test/__new__" is not mounted or cannot be found.

**Comment by leofeyer** [comment]
Das lässt sich relativ einfach beheben, indem wir aus [Zeile 116](https://github.com/contao/core-bundle/blob/develop/src/Resources/contao/drivers/DC_Folder.php#L116)

```php
$this->intId = rawurldecode(\Input::get('id', true));
```

machen. @ausi Irgendwelche Sicherheitsbedenken?

**Comment by ausi** [comment]
Ich denke das wäre die falsche Stelle für die Lösung des Fehlers und es könnte andere Probleme verursachen.

Das Problem liegt in [DC_Folder.php:588](https://github.com/contao/core-bundle/blob/1448b9d4a9faa9f3fcf6e5518d8bb159bf7f1821/src/Resources/contao/drivers/DC_Folder.php#L588) dort wird der Ordner durch `$this->urlEncode()` kodiert obwohl direkt danach in `DataContainer::switchToEdit()` in [DataContainer.php:649](https://github.com/contao/core-bundle/blob/1448b9d4a9faa9f3fcf6e5518d8bb159bf7f1821/src/Resources/contao/classes/DataContainer.php#L649) der Parameter erneut URL-kodiert wird. Ich denke in `DC_Folder` sollte der `urlEncode()`-Aufruf entfernt werden sodass die Zeile danach so aussieht:

```php
$this->redirect(html_entity_decode($this->switchToEdit($strFolder . '/__new__')));
```

In meinem Test hat der Fix funktioniert.

**Comment by leofeyer** [comment]
Behoben in https://github.com/contao/core-bundle/commit/8691d3fd47386c2ccb2c9c1b8c2128699c51f6a1. Danke @ausi
